### ISSUE TITLE
AppImage not unmounting when running as systemd service

### ISSUE THREAD

**Issue by nickjmeyer** [AppImage/AppImageKit#1362]
I have an AppImage that when run on the command line, works just fine.  Executes as expected and cleans up the mount point on exit. However, when run as a systemd service, regardless if it exists cleanly or with a failure, the mount point is left behind in `/tmp`.  This ends up accumulating a bunch of stale fuse mounts and after long enough the mount limit is reached and no more appimages can be run.

Any ideas why running as a systemd service might prevent the mount point from getting cleaned up?

**Comment by probonopd** [comment]
While the service is running, the AppImage should be mounted. Once the application inside the AppImage exits, the AppImage should get unmounted. This only works when the application inside the AppImage is quit properly. How does the application inside your AppImage get quit?

**Comment by nickjmeyer** [comment]
I was able to reproduce this behavior with the following minimal example program:
```
int main() { return 0; }
```

**Comment by probonopd** [comment]
Then I don't know the answer to your question as I have never tried to run applications with systemd.

**Comment by nickjmeyer** [comment]
I've noticed fuse mounts are fussy with users.  For example, I've tried to shell out to a sub-command prefixed with `sudo` and from some research it seems the  `allow_user` config flat is needed to allow other users besides the one who mounted it to execute within the mount.

Any chance there is something similar regarding the unmounting?

**Comment by probonopd** [comment]
Just to be sure, in your minimal example program your AppImage properly unmounts when NOT launched by systemd?

As which user is systemd running your AppImage?

**Comment by nickjmeyer** [comment]
>Just to be sure, in your minimal example program your AppImage properly unmounts when NOT launched by systemd?

That's correct.  The AppImage works just as expected when run outside systemd (e.g., on the command line).

>As which user is systemd running your AppImage?

I might be misunderstanding the question, but I'm running the service with this line in the service file to specify the user:
```
[Service]
User=myuser
```

**Comment by probonopd** [comment]
Unfortunately I don't know the answer, or how to debug this. But we can leave this issue open in case someone more knowledgeable about systemd sees this.

**Comment by nickjmeyer** [comment]
Sounds good.  Thanks for chiming in so quickly!

**Comment by probonopd** [comment]
Please retry with an AppImage made using the latest https://github.com/AppImage/appimagetool/releases/tag/continuous, it might have been fixed in the lastest AppImage runtime by

* https://github.com/AppImage/type2-runtime/pull/93

**Comment by nickjmeyer** [comment]
I extracted the appimage I used before and created a new one from that AppDir using the latest `appimagetool`.  However, I'm still seeing the same issue.  It appears to be the same issue @lalten saw in https://github.com/AppImage/type2-runtime/issues/92.

I tested this service file (appimage.service):
```
[Unit]
Description=Testing appimages

[Service]
Type=oneshot
ExecStart=/home/nickjmeyer/appimage_test_new.AppImage

[Install]
WantedBy=multi-user.target
```

Using the following:
```
sudo systemctl enable /path/to/appimage.service
sudo systemctl start appimage.service
```

It works sometimes, but then other times the appimage hangs on exit.  I'll see stdout in `journalctl -u appimage.service`, but the call to `systemctl start` hangs.  When this occurs, I'll see an orphaned mount in `/tmp`.
